---
book_repo: pivotal-cf/docs-book-cloud-cache
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: 'v1.2-branch'
    at_path: content
  directory: p-cloud-cache/1-2
  subnav_template: cloudcache_subnav-1-2.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.1
    changelog_href: http://docs.pivotal.io/p-cloud-cache/1-1/index.html#release-notes
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Cloud Cache for PCF
    search_placeholder: Search Pivotal Cloud Cache for PCF 1.2
    url_prefix: p-cloud-cache/1-2
    local_product_version: 1.2
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/p-cloud-cache/1-0
        display_name: v1.0

- repository:
    name: pivotal-cf/docs-on-demand-service-broker
    ref: v0.17.x
  directory: p-cloud-cache/odb
  no_docs: true

