---
book_repo: pivotal-cf/docs-book-cloud-cache
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
public_host: docs.pivotal.io
feedback_enabled: true
repo_link_enabled: true
elastic_search: true

pcf_header: &local_pcc
  use_local_header: true
  latest_stable_version: 1.9
  changelog_href: /p-cloud-cache/1-9/release-notes.html
  local_header_img: /images/pivotal-cloud-cache-icon.png
  local_header_title: Pivotal Cloud Cache
  search_placeholder: Search PCC v1.9
  url_prefix: p-cloud-cache/1-9/
  local_product_version: 1.9
  local_header_links: []
  local_header_version_list:
    - url_prefix: /p-cloud-cache/1-8/
      display_name: v1.8
    - url_prefix: /p-cloud-cache/1-7/
      display_name: v1.7
    - url_prefix: /p-cloud-cache/1-6/
      display_name: v1.6
    - url_prefix: /p-cloud-cache/1-5/
      display_name: v1.5
    - url_prefix: /p-cloud-cache/1-4/
      display_name: v1.4
    - <a href="http://docs.pivotal.io/archives/p-cloud-cache-1.3.5.pdf">v1.2</a>
    - <a href="http://docs.pivotal.io/archives/p-cloud-cache-1.2.2.pdf">v1.2</a>
    - <a href="http://docs.pivotal.io/archives/p-cloud-cache-1.1.5.pdf">v1.1</a>
    - <a href="http://docs.pivotal.io/archives/p-cloud-cache-1.0.8.pdf">v1.0</a>

sections:
- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: master
    at_path: content
  directory: p-cloud-cache/1-9
  subnav_template: cloudcache_subnav
  product_info: *local_pcc
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: p-cloud-cache/partials
  no_docs: true

# For template variables, see config/template_variables.yml. Use format <%=vars.VARIABLE_NAME_HERE%> to insert the following into content. Note: Bookbinder will not convert template variables inserted into config.yml or redirects.rb.

broken_link_exclusions: iefix|arrowhead|1-3|1-4|1-5|1-6|1-7|1-8
