---
book_repo: pivotal-cf/docs-book-cloud-cache
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
public_host: docs.pivotal.io
feedback_enabled: true
repo_link_enabled: true
elastic_search: true

pcf_header: &local_pcc
  use_local_header: true
  latest_stable_version: '1.10'
  changelog_href: /p-cloud-cache/1-10/release-notes.html
  local_header_img: /images/pivotal-cloud-cache-icon.png
  local_header_title: Pivotal Cloud Cache
  search_placeholder: Search PCC v1.10
  url_prefix: p-cloud-cache/1-10/
  local_product_version: '1.10'
  local_header_links:
    - <a href="https://docs.pivotal.io/cloud-cache-dev/">Cloud Cache Developer Guide</a>
    - <a href="https://support.pivotal.io">Ask for Help</a>
  local_header_version_list:
    - url_prefix: /p-cloud-cache/1-13/
      display_name: v1.13
    - url_prefix: /p-cloud-cache/1-12/
      display_name: v1.12
    - url_prefix: /p-cloud-cache/1-11/
      display_name: v1.11
    - url_prefix: /p-cloud-cache/1-9/
      display_name: v1.9

sections:
- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: v1.10-branch
    at_path: content
  directory: 'p-cloud-cache/1-10'
  subnav_template: cloudcache_subnav
  product_info: *local_pcc
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: p-cloud-cache/partials
  no_docs: true

# For template variables, see config/template_variables.yml. Use format <%=vars.VARIABLE_NAME_HERE%> to insert the following into content. Note: Bookbinder will not convert template variables inserted into config.yml or redirects.rb.

broken_link_exclusions: iefix|arrowhead|1-3|1-4|1-5|1-6|1-7|1-8|1-9|1-11|1-12|1-13
