---
book_repo: pivotal-cf/docs-book-cloud-cache
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
public_host: docs.pivotal.io
feedback_enabled: true
repo_link_enabled: true
elastic_search: true

pcf_header: &local_pcc
  use_local_header: true
  latest_stable_version: '1.13'
  changelog_href: /p-cloud-cache/1-13/release-notes.html
  local_header_img: /images/pivotal-cloud-cache-icon.png
  local_header_title: VMware Tanzuâ„¢ GemFire&reg; for VMs
  search_placeholder: Search Tanzu GemFire v1.13
  url_prefix: p-cloud-cache/1-13/
  local_product_version: '1.13'
  local_header_links:
    - <a href="https://tanzu.vmware.com/developer/data/tanzu-gemfire/">Tanzu GemFire&reg; Developer Guide</a>
    - <a href="https://support.pivotal.io">Ask for Help</a>
    - <p style="background-color:#ddd;padding:8px"><a href="/p-cloud-cache/1-13/release-notes.html">Pivotal Cloud Cache is now<br /><strong>VMware Tanzu GemFire!</strong></a></p>
  local_header_version_list:
    - url_prefix: /p-cloud-cache/1-12/
      display_name: v1.12
    - url_prefix: /p-cloud-cache/1-11/
      display_name: v1.11
    - url_prefix: /p-cloud-cache/1-10/
      display_name: v1.10
    - url_prefix: /p-cloud-cache/1-9/
      display_name: v1.9

sections:
- repository:
    name: pivotal-cf/docs-cloud-cache
    ref: v1.13-branch
    at_path: content
  directory: 'p-cloud-cache/1-13'
  subnav_template: cloudcache_subnav
  product_info: *local_pcc
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: p-cloud-cache/partials
  no_docs: true

# For template variables, see config/template_variables.yml. Use format <%=vars.VARIABLE_NAME_HERE%> to insert the following into content. Note: Bookbinder will not convert template variables inserted into config.yml or redirects.rb.

broken_link_exclusions: iefix|arrowhead|1-3|1-4|1-5|1-6|1-7|1-8|1-9|1-10|1-11|1-12
